# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('fatherName', models.CharField(max_length=60)),
                ('motherName', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('addressProof', models.ImageField(upload_to='addressProof')),
                ('idProof', models.ImageField(upload_to='idProof')),
                ('panNumber', models.IntegerField(default=0)),
                ('panCard', models.ImageField(upload_to='panCard')),
                ('accountType', models.CharField(choices=[('S', 'Saving'), ('C', 'Current')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+9999999'. Upto 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('fatherName', models.CharField(max_length=60)),
                ('motherName', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('idProof', models.ImageField(upload_to='idProof')),
                ('addressProof', models.ImageField(upload_to='addressProof')),
                ('panNumber', models.IntegerField(default=0)),
                ('panCard', models.ImageField(upload_to='panCard')),
                ('incomeProof', models.ImageField(upload_to='incomeProof')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+9999999'. Upto 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
