# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('formNumber', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=60)),
                ('fatherName', models.CharField(max_length=60)),
                ('motherName', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('addressProof', models.ImageField(upload_to='addressProof')),
                ('idProof', models.ImageField(upload_to='idProof')),
                ('panNumber', models.IntegerField(unique=True)),
                ('panCard', models.ImageField(upload_to='panCard')),
                ('accountType', models.CharField(choices=[('S', 'Saving'), ('C', 'Current')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+9999999'. Upto 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('startingAmount', models.IntegerField()),
                ('formStatus', models.CharField(choices=[('RP', 'Request pending'), ('VF', 'Verified but found false'), ('VT', 'Verified and found true'), ('AC', 'Account created')], default='RP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('fatherName', models.CharField(max_length=60)),
                ('motherName', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('idProof', models.ImageField(upload_to='idProof')),
                ('addressProof', models.ImageField(upload_to='addressProof')),
                ('panNumber', models.IntegerField()),
                ('panCard', models.ImageField(upload_to='panCard')),
                ('incomeProof', models.ImageField(upload_to='incomeProof')),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+9999999'. Upto 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('cardType', models.CharField(choices=[('B', 'Bronz'), ('S', 'Silver'), ('G', 'Gold')], max_length=1)),
            ],
        ),
    ]
