# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrequest',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='creditcardrequest',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='cardType',
            field=models.CharField(choices=[('B', 'Bronz'), ('S', 'Silver'), ('G', 'Gold')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
