# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('debitCardNumber', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowNumber', models.IntegerField(unique=True)),
                ('accountNumberStarting', models.IntegerField()),
                ('debitCardStarting', models.IntegerField()),
                ('creditCardStarting', models.IntegerField()),
                ('accountRequestCount', models.IntegerField()),
                ('creditCardRequestCount', models.IntegerField()),
                ('accountsCount', models.IntegerField()),
                ('creditCardCount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='panNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='formNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.AccountRequest'),
        ),
    ]
