# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20170203_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitCardNumber', models.CharField(max_length=16, unique=True)),
                ('validFromMonth', models.IntegerField()),
                ('validFromYear', models.IntegerField()),
                ('validThruMonth', models.IntegerField()),
                ('validThruYear', models.IntegerField()),
                ('lottNo', models.IntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='debitCardNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.DebitCard'),
        ),
    ]
