# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20170129_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='startingAmount',
            field=models.IntegerField(default=0),
        ),
    ]
