# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0005_auto_20170204_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('creditedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditedTo', to='banking.Account')),
                ('debitedFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitedFrom', to='banking.Account')),
            ],
        ),
    ]
